### ISSUE TITLE
Wrong owner/permissions on /etc/rabbitmq/enabled_plugins

### ISSUE THREAD

**Issue by dgmorales** [stone-payments/ansible-rabbitmq#1]
There is some situation where /etc/rabbitmq/enabled_plugins ends up with wrong permissions (like root.root 600), and then rabbitmq fails to start.

We weren't able to test it more yet, but maybe the plugin enablement task overwrites the permission that is correctly set before.

**Comment by fffialho** [comment]
That has been fixed in version 2.0.0.
Version 3.0.0 adds idempotency to this specific task and to the whole role as well.
