### ISSUE TITLE
Rabbitmq role doesn't work with FQDN

### ISSUE THREAD

**Issue by guilhermeoki** [stone-payments/ansible-rabbitmq#11]
Version of rabbitmq: 3.6.15
Version of ansible: 2.5.2

Some related issues https://github.com/rabbitmq/rabbitmq-server/issues/1182

I'll do a fix to this role right now.

TASK [stone-payments.rabbitmq : join rabbitmq cluster] ********************************************************************************************************************************
Monday 25 June 2018  20:26:34 +0000 (0:00:01.795)       0:07:28.033 ***********
skipping: [rabbitmq-1p01.example.com]
fatal: [rabbitmq-1p02.example.com]: FAILED! => {"changed": true, "cmd": ["rabbitmqctl", "join_cluster", "rabbit@rabbitmq-1p01.example.com"], "delta": "0:00:00.593572", "end": "2018-06-25 20:26:36.236655", "msg": "non-zero return code", "rc": 69, "start": "2018-06-25 20:26:35.643083", "stderr": "Error: unable to connect to nodes ['rabbit@rabbitmq-1p01.example.com']: nodedown\n\nDIAGNOSTICS\n===========\n\nattempted to contact: ['rabbit@rabbitmq-1p01.example.com']\n\nrabbit@rabbitmq-1p01.example.com:\n  * connected to epmd (port 4369) on rabbitmq-1p01.example.com\n  * epmd reports node 'rabbit' running on port 25672\n  * TCP connection succeeded but Erlang distribution failed\n  * suggestion: hostname mismatch?\n  * suggestion: is the cookie set correctly?\n  * suggestion: is the Erlang distribution using TLS?\n\ncurrent node details:\n- node name: 'rabbitmq-cli-43@rabbitmq-1p02'\n- home dir: /var/lib/rabbitmq\n- cookie hash: CK4sp2CJBEqH0+fQ6bhdrQ==", "stderr_lines": ["Error: unable to connect to nodes ['rabbit@rabbitmq-1p01.example.com']: nodedown", "", "DIAGNOSTICS", "===========", "", "attempted to contact: ['rabbit@rabbitmq-1p01.example.com']", "", "rabbit@rabbitmq-1p01.example.com:", "  * connected to epmd (port 4369) on rabbitmq-1p01.example.com", "  * epmd reports node 'rabbit' running on port 25672", "  * TCP connection succeeded but Erlang distribution failed", "  * suggestion: hostname mismatch?", "  * suggestion: is the cookie set correctly?", "  * suggestion: is the Erlang distribution using TLS?", "", "current node details:", "- node name: 'rabbitmq-cli-43@rabbitmq-1p02'", "- home dir: /var/lib/rabbitmq", "- cookie hash: CK4sp2CJBEqH0+fQ6bhdrQ=="], "stdout": "Clustering node 'rabbit@rabbitmq-1p02' with 'rabbit@rabbitmq-1p01.example.com'", "stdout_lines": ["Clustering node 'rabbit@rabbitmq-1p02' with 'rabbit@rabbitmq-1p01.example.com'"]}
fatal: [rabbitmq-1p03.example.com]: FAILED! => {"changed": true, "cmd": ["rabbitmqctl", "join_cluster", "rabbit@rabbitmq-1p01.example.com"], "delta": "0:00:00.621648", "end": "2018-06-25 20:26:36.268335", "msg": "non-zero return code", "rc": 69, "start": "2018-06-25 20:26:35.646687", "stderr": "Error: unable to connect to nodes ['rabbit@rabbitmq-1p01.example.com']: nodedown\n\nDIAGNOSTICS\n===========\n\nattempted to contact: ['rabbit@rabbitmq-1p01.example.com']\n\nrabbit@rabbitmq-1p01.example.com:\n  * connected to epmd (port 4369) on rabbitmq-1p01.example.com\n  * epmd reports node 'rabbit' running on port 25672\n  * TCP connection succeeded but Erlang distribution failed\n  * suggestion: hostname mismatch?\n  * suggestion: is the cookie set correctly?\n  * suggestion: is the Erlang distribution using TLS?\n\ncurrent node details:\n- node name: 'rabbitmq-cli-09@rabbitmq-1p03'\n- home dir: /var/lib/rabbitmq\n- cookie hash: CK4sp2CJBEqH0+fQ6bhdrQ==", "stderr_lines": ["Error: unable to connect to nodes ['rabbit@rabbitmq-1p01.example.com']: nodedown", "", "DIAGNOSTICS", "===========", "", "attempted to contact: ['rabbit@rabbitmq-1p01.example.com']", "", "rabbit@rabbitmq-1p01.example.com:", "  * connected to epmd (port 4369) on rabbitmq-1p01.example.com", "  * epmd reports node 'rabbit' running on port 25672", "  * TCP connection succeeded but Erlang distribution failed", "  * suggestion: hostname mismatch?", "  * suggestion: is the cookie set correctly?", "  * suggestion: is the Erlang distribution using TLS?", "", "current node details:", "- node name: 'rabbitmq-cli-09@rabbitmq-1p03'", "- home dir: /var/lib/rabbitmq", "- cookie hash: CK4sp2CJBEqH0+fQ6bhdrQ=="], "stdout": "Clustering node 'rabbit@rabbitmq-1p03' with 'rabbit@rabbitmq-1p01.example.com'", "stdout_lines": ["Clustering node 'rabbit@rabbitmq-1p03' with 'rabbit@rabbitmq-1p01.example.com'"]}

**Comment by douglasquintanilha** [comment]
Added support on role version v1.3.0
