### ISSUE TITLE
Python cryptography=2.2.2 in requirements.txt has known vulnerability

### ISSUE THREAD

**Issue by dgmorales** [stone-payments/ansible-rabbitmq#16]
Gihub is generating an alert about this. I see the requirements.txt has very old versions (ansible 2.5.0, for example). An overall refresh on it would be nice.

I guess that is used only by ansible, when ansible is run using an env that sourced this file. not a big deal, but we should not ignore this alerts too long :D

**Comment by igordcsouza** [comment]
@dgmorales tem esse PR do @douglasquintanilha para resolver esse problema.
https://github.com/stone-payments/ansible-rabbitmq/pull/18
