### ISSUE TITLE
Publish role to Ansigle Galaxy

### ISSUE THREAD

**Issue by willianpaixao** [stone-payments/ansible-rabbitmq#25]
Apparently this role `stone-payments.rabbitmq` is not yet published to [Ansible Galaxy](https://galaxy.ansible.com), is that correct?

``` bash
$ ansible-galaxy install stone-payments.rabbitmq
- downloading role 'rabbitmq', owned by stone-payments
[WARNING]: - stone-payments.rabbitmq was NOT installed successfully: - sorry, stone-payments.rabbitmq was not found on https://galaxy.ansible.com/api/.
ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.
```

**Comment by fffialho** [comment]
I don't think that is acceptable by the current enterprise policy.
We use Galaxy by integrating it through git repository referred to as dependant roles.
