### ISSUE TITLE
Specify password for new users

### ISSUE THREAD

**Issue by willianpaixao** [stone-payments/ansible-rabbitmq#26]
As for right now, the password of new users is the same of the username.
Would be nice to have a map with username and passwords to improve security. [[1]](https://github.com/stone-payments/ansible-rabbitmq/blob/5b8f2e128c9600232d69a5a99165215bb3a01178/tasks/configuration.yml#L72)

**Comment by fffialho** [comment]
Hey! @willianpaixao, that will be possible using the new version 3.0.0 that will be released soon. Stay tuned!
