### ISSUE TITLE
Set erlang cookie regardless of  cluster

### ISSUE THREAD

**Issue by willianpaixao** [stone-payments/ansible-rabbitmq#27]
In some cases, you want to set a specific Erlang cookie even if there's no cluster to be configured.
I suggest either moving or duplicating the task of setting the cookie file.

**Comment by fffialho** [comment]
@willianpaixao, Hi Willian, could you bring some example of that situation, please?

**Comment by fffialho** [comment]
@willianpaixao! Version 3.0.0 has been changed to meet your request.
